// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Hotel.Entity
{
    public partial class Guests
    {
        public int id { get; set; }
        public string GuestNationalNumber { get; set; }
        public string GuestFullName { get; set; }
        public int GuestRoomNumber { get; set; }
        public string ClientNationalNumber { get; set; }
        public DateTime CheckInDate { get; set; }
        public DateTime CheckOutDate { get; set; }
    }
}