// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Hotel.Entity
{
    public partial class HotelContext : DbContext
    {
        public HotelContext()
        {
        }

        public HotelContext(DbContextOptions<HotelContext> options)
            : base(options)
        {
        }
         

        public virtual DbSet<Reservations> Reservations { get; set; }
        public virtual DbSet<RoomPrice> RoomPrice { get; set; }
        public virtual DbSet<RoomTypes> RoomTypes { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Reservations>(entity =>
            {
                entity.Property(e => e.CheckInDate).HasColumnType("datetime");

                entity.Property(e => e.CheckOutDate).HasColumnType("datetime");

                entity.Property(e => e.ClientFullName)
                    .IsRequired()
                    .HasMaxLength(250)
                    .IsFixedLength();

                entity.HasOne(d => d.RoomType)
                    .WithMany(p => p.Reservations)
                    .HasForeignKey(d => d.RoomTypeId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Resevations_RoomType");
            });

            modelBuilder.Entity<RoomPrice>(entity =>
            {
                entity.Property(e => e.CreateDate).HasColumnType("datetime");

                entity.Property(e => e.RoomPrice1)
                    .HasColumnName("RoomPrice")
                    .HasColumnType("decimal(18, 0)");

                entity.HasOne(d => d.RoomType)
                    .WithMany(p => p.RoomPrice)
                    .HasForeignKey(d => d.RoomTypeId)
                    .HasConstraintName("FK_RoomPrice_RoomType");
            });

            modelBuilder.Entity<RoomTypes>(entity =>
            {
                entity.Property(e => e.RoomType).HasMaxLength(100);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}