// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Hotel.Entity
{
    public partial class Reservations
    {
        public int id { get; set; }
        public int RoomTypeId { get; set; }
        public string ClientFullName { get; set; }
        public DateTime CheckInDate { get; set; }
        public DateTime CheckOutDate { get; set; }
        public int? FranchPad { get; set; }

        public virtual RoomTypes RoomType { get; set; }
    }
}