// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Hotel.Entity
{
    public partial class RoomTypes
    {
        public RoomTypes()
        {
            Reservations = new HashSet<Reservations>();
            RoomPrice = new HashSet<RoomPrice>();
        }

        public int id { get; set; }      
        public string RoomType { get; set; }
        public int Bed { get; set; }
        public string BedType { get; set; }

        public virtual ICollection<Reservations> Reservations { get; set; }
        public virtual ICollection<RoomPrice> RoomPrice { get; set; }
    }
}