// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Hotel.Entity
{
    public partial class RoomPrice
    {
        public int id { get; set; }
        public int? RoomTypeId { get; set; }
        public decimal? RoomPrice1 { get; set; }
        public DateTime? CreateDate { get; set; }

        public virtual RoomTypes RoomType { get; set; }
    }
}